// MOVIES
export const MOVIES_START_DISCOVERING_LIST = 'MOVIES_START_DISCOVERING_LIST';
export const MOVIES_END_DISCOVERING_LIST = 'MOVIES_END_DISCOVERING_LIST';
export const MOVIES_ERROR_DISCOVERING_LIST = 'MOVIES_ERROR_DISCOVERING_LIST';
export const MOVIES_START_SEARCHING_LIST = 'MOVIES_START_SEARCHING_LIST';
export const MOVIES_END_SEARCHING_LIST = 'MOVIES_END_SEARCHING_LIST';
export const MOVIES_ERROR_SEARCHING_LIST = 'MOVIES_ERROR_SEARCHING_LIST';
export const MOVIES_SET_SORT_BY = 'MOVIES_SET_SORT_BY';
export const MOVIES_SET_PAGE = 'MOVIES_SET_PAGE';
export const MOVIES_SET_QUERY = 'MOVIES_SET_QUERY';

// MOVIE
export const MOVIE_START_FETCHING_INFO = 'MOVIE_START_FETCHING_INFO';
export const MOVIE_END_FETCHING_INFO = 'MOVIE_END_FETCHING_INFO';
export const MOVIE_ERROR_FETCHING_INFO = 'MOVIE_ERROR_FETCHING_INFO';

// LANGUAGE
export const LANGUAGE_SET_LANGUAGE = 'LANGUAGE_SET_LANGUAGE';

// TV SHOWS
export const TVSHOWS_START_DISCOVERING_LIST = 'TVSHOWS_START_DISCOVERING_LIST';
export const TVSHOWS_END_DISCOVERING_LIST = 'TVSHOWS_END_DISCOVERING_LIST';
export const TVSHOWS_ERROR_DISCOVERING_LIST = 'TVSHOWS_ERROR_DISCOVERING_LIST';
export const TVSHOWS_START_SEARCHING_LIST = 'TVSHOWS_START_SEARCHING_LIST';
export const TVSHOWS_END_SEARCHING_LIST = 'TVSHOWS_END_SEARCHING_LIST';
export const TVSHOWS_ERROR_SEARCHING_LIST = 'TVSHOWS_ERROR_SEARCHING_LIST';
export const TVSHOWS_SET_SORT_BY = 'TVSHOWS_SET_SORT_BY';
export const TVSHOWS_SET_PAGE = 'TVSHOWS_SET_PAGE';
export const TVSHOWS_SET_QUERY = 'TVSHOWS_SET_QUERY';

// TV SHOW
export const TVSHOW_START_FETCHING_INFO = 'TVSHOW_START_FETCHING_INFO';
export const TVSHOW_END_FETCHING_INFO = 'TVSHOW_END_FETCHING_INFO';
export const TVSHOW_ERROR_FETCHING_INFO = 'TVSHOW_ERROR_FETCHING_INFO';
